df %>% group_by(name, SEQUENCE) %>% dplyr::summarise(same_scaff=paste(unique(GENE), collapse=" ")) %>% View()
df %>% group_by(name, SEQUENCE) %>% dplyr::summarise(same_scaff=paste(unique(GENE), collapse=" ")) %>% View()
df_by_scaff <- df %>% group_by(name, SEQUENCE) %>% dplyr::summarise(same_scaff=paste(unique(GENE), collapse=" "))
df_by_scaff %>% filter(grepl("IncX", same_scaff))
df_by_scaff %>% filter(grepl("IncX", same_scaff)) %>% unique(.$same_scaff)
df_by_scaff %>% filter(grepl("IncX", same_scaff)) %>% unique(same_scaff
)
IncX_scaffs <- df_by_scaff %>% filter(grepl("IncX", same_scaff))
unique(IncX_scaffs$same_scaff)
View(IncX_scaffs)
table(IncX_scaffs$same_scaff)
table(IncX_scaffs$same_scaff) %>% View()
df_by_scaff <- df %>% group_by(name, SEQUENCE) %>% dplyr::summarise(same_scaff=paste(sort(unique(GENE)), collapse=" "))
IncX_scaffs <- df_by_scaff %>% filter(grepl("IncX", same_scaff))
table(IncX_scaffs$same_scaff) %>% View()
IncX_scaffs <- df_by_scaff %>% filter(grepl("IncX", same_scaff)) %>% filter(grepl("qnrS1", same_scaff))  filter(grepl("tet", same_scaff))
IncX_scaffs <- df_by_scaff %>% filter(grepl("IncX", same_scaff)) %>% filter(grepl("qnrS1", same_scaff)) %>% filter(grepl("tet", same_scaff))
View(IncX_scaffs)
df_by_scaff <- df %>% group_by(name, SEQUENCE) %>% dplyr::summarise(same_scaff=paste(sort(unique(GENE)), collapse=" "))
IncX_scaffs <- df_by_scaff %>% filter(grepl("IncX", same_scaff))
IncX_scaffs  %>% filter(grepl("qnrS1", same_scaff)) %>% filter(grepl("tet", same_scaff))
table(IncX_scaffs$same_scaff) %>% as.data.frame() %>% filter(grepl("qnrS1", same_scaff)) %>% filter(grepl("tet", same_scaff))
table(IncX_scaffs$same_scaff) %>% as.data.frame()
unique_IncX_scaffs <- table(IncX_scaffs$same_scaff) %>% as.data.frame()
unique_IncX_scaffs %>%filter(grepl("qnrS1", same_scaff)) %>% filter(grepl("tet", same_scaff))
unique_IncX_scaffs %>%filter(grepl("qnrS1", Var1)) %>% filter(grepl("tet", Var1))
33 + 4 + 17 + 5 + 2 + 2 + 1 + 1
